version: "3.1"

services:
  backend:
    build: ./reactproject
    expose:
      - 8080
    command: gunicorn reactproject.wsgi -b 0.0.0.0:8080
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend/learnapp
    ports:
      - 80:80
    depends_on:
      - nginx