# Generated by Django 4.1 on 2022-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=32)),
                ('ru', models.CharField(max_length=32)),
                ('learned', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('show_translate', models.BooleanField(default=False)),
            ],
        ),
    ]
